<?php
declare(strict_types=1);

namespace Rabbit\Server;


use Rabbit\Base\Core\Exception;

/**
 * Class TaskException
 * @package rabbit\server
 */
class TaskException extends Exception
{
    public function getName(): string
    {
        return 'Task Exception'; // TODO: Change the autogenerated stub
    }
}
