<?php


namespace rabbit\server;

use rabbit\core\Exception;

/**
 * Class TaskException
 * @package rabbit\server
 */
class TaskException extends Exception
{
    public function getName(): string
    {
        return 'Task Exception'; // TODO: Change the autogenerated stub
    }
}
